### ISSUE TITLE
这个插件导致历史和日志不正常

### ISSUE THREAD

**Issue by maybeloveu** [gexing147/homeassistant_zinguo#2]
使用这个插件后发现日志启动后不在更新，历史记录里也不记录数据。排查了好久发现是这个插件导致的。论坛也有其他人有同样问题。期待解决。

**Comment by FR-Chelsea** [comment]
同楼上的 一样的问题

**Comment by cctv838126** [comment]
同样的问题，求解决~~

**Comment by keniji** [comment]
同.. 出现一样的问题, 看了日志发现插件隔1秒就扫一遍, 估计是占用了所有资源吧.. 看看能不能加一个扫描间隔, 比如5秒10秒的.

**Comment by maybeloveu** [comment]
https://bbs.hassbian.com/thread-6203-1-1.html
我用node-red重新写了个。不存在上面的问题。优化了更新逻辑。有问题的去上面链接。

**Comment by keniji** [comment]
> https://bbs.hassbian.com/thread-6203-1-1.html
> 我用node-red重新写了个。不存在上面的问题。优化了更新逻辑。有问题的去上面链接。

"抱歉，本帖要求阅读权限高于 30 才能浏览", 尴尬...

**Comment by FR-Chelsea** [comment]
> https://bbs.hassbian.com/thread-6203-1-1.html
> 我用node-red重新写了个。不存在上面的问题。优化了更新逻辑。有问题的去上面链接。

大神，能否多个支持？

**Comment by gexing147** [comment]
已修复日志问题
